blank_issues_enabled: false
contact_links:
  - name: Development Help
    about: Help on the Development
    url: https://github.com/Optimum-off/Template/discussions
  - name: Usage Help
    about: Help on the Usage
    url: https://discord.gg/invite
